# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Felipe Klein Zigmundo'
tagline:          'Personal Blog'
description:      '--'
url:              http://felipekzig.github.io
baseurl:          /

author:
  name:           'Felipe Klein Zigmundo'
  url:            https://twitter.com/felipekzig

paginate:         1

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/felipekzig/felipekzig.github.io
